# order-service configuration file

#port
server:
  port: 8083

# Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_order_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate JPA settings
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
